### ISSUE TITLE
EmitAsync doesn't work

### ISSUE THREAD

**Issue by KevinCeyland** [doghappy/socket.io-client-csharp#134]
Hello,

When I do an EmitAsync of an event to receive it in my nodeJS server I get nothing no events go off, I have tried all of them, do you have a solution to make this work?

C# :

```cs 
client.OnConnected += async (a, b) => {
    await client.EmitAsync("hi", "Je suis connecté");
};
await client.ConnectAsync();
```

NodeJS :

```js
socket.on("hi", name => {
    console.log("hello");
});
```

**Comment by doghappy** [comment]
Make sure that the OnConnected event is triggered.

```cs
client.OnConnected += async (a, b) => {
    Console.WriteLine("OnConnected");
    await client.EmitAsync("hi", "Je suis connecté");
};
await client.ConnectAsync();
```

You can add a log or detect whether an event is triggered by a breakpoint.

**Comment by KevinCeyland** [comment]
Yes is triggered but not the emit ;(

The problem does not come from the fact that it is asynchronous ?

**Comment by doghappy** [comment]
Can you provide a reproducible github repo, including socket.io server and client?

**Comment by KevinCeyland** [comment]
Yes no worries, just before I will try to deploy it on my server and do some test, then I will put it on a github repo.

**Comment by whoishina** [comment]
+1 Problem

**Comment by doghappy** [comment]
Please provide more information

**Comment by whoishina** [comment]
#### Versions
- Socket.io Server version: 2.4.1
- .Net Framework 4.5.1
- Socket.io-client version : 2.0.2.10

All Event OnConnected, Disconnect, Retry is working well. But i cant EmitAsync to Server.

#### Client
```C#
private static async void Socket_OnConnected(object sender, EventArgs e)
{
    Console.WriteLine("Socket.io Connected");

    var socket = sender as SocketIO;

    Console.WriteLine("Socket.Id:" + socket.Id);

    await socket.EmitAsync("Super", new
    {
        test = 100,
    });
}
```

#### Server 
```JS
server.on("connection", socket => {

    console.log("new connection!")

    socket.on("Super", data => {
        console.log("Log From Client")
    })

})
```

**Comment by whoishina** [comment]
I've check back my server config and this problem was resolved.

**Comment by KevinCeyland** [comment]
I still have the same problem, the emitasync is not working, is it because I am local? I add you one to a github repo doghappy.

**Comment by doghappy** [comment]
@KevinCeyland I pushed 2 commits to your repo. It seems that you are using socket.io server incorrectly.

Send cmd broadcast from index.html, the client can also receive it.

![image](https://user-images.githubusercontent.com/20038914/127597014-b3987d10-5fce-48a4-8def-9f722e362660.png)

**Comment by KevinCeyland** [comment]
Thanks !! it works, on the other hand I cannot do an emitAsync outside : 

client.OnConnected += async(a,b) => { 
      
}
How can I send data like the IP back to my web interface ?

**Comment by doghappy** [comment]
I pushed a commit. When the client connects/disconnects, the ip list of the html interface will be updated
