### ISSUE TITLE
client event receiving slows down

### ISSUE THREAD

**Issue by dotriz** [doghappy/socket.io-client-csharp#149]
I am using socket.io client to send file upload progress from WPF app to other connected clients.
When app is uploading file, and sending progress it's pretty fast. See https://share.getcloudapp.com/xQu798eA

But when other client sends progress to WPF app, its really slow. And during receiving series of events, it gets stuck and disconnect too. See https://share.getcloudapp.com/WnuxwP44
In this video, at one minute time, all the file was uploaded with all events sent from other client, but Windows app was around 5%

Can you suggest what could be causing WPF app to stuck/slow down at receiving events?

**Comment by doghappy** [comment]
I pushed some code and released the version `v2.2.1-alpha.1`. You can pull or install the preview version, fixed disconnection issue.

I very much hope to receive your feedback again.

Is wpf still very slow to send data?

**Comment by doghappy** [comment]
Fixed, please upgrade to `v2.2.1`

**Comment by dotriz** [comment]
@doghappy issue is still there in v2.2.1. Sending update is pretty much fine and quick, but receiving slows down when there are lot of events coming ( like I mentioned file upload progress is shared ).

**Comment by doghappy** [comment]
Thanks for your feedback, I have resolved it.

https://github.com/doghappy/socket.io-client-csharp/commit/371eb72c0c2a387426d45cc9eeb9bf04f4077d02

I increased the buffer size, it seems that 16k is a reasonable value.

upgrade to `v2.2.2`
